CREATE TABLE `survey_responses_flat` (
	`id` int AUTO_INCREMENT NOT NULL,
	`surveyId` int NOT NULL,
	`surveyType` enum('visitantes','residentes') NOT NULL,
	`surveyNumber` varchar(8),
	`surveyPoint` varchar(255),
	`timeSlot` varchar(32),
	`windowCode` varchar(16),
	`minuteStart` varchar(5),
	`minuteEnd` varchar(5),
	`encuestadorId` int NOT NULL,
	`encuestadorName` varchar(255),
	`encuestadorCode` varchar(32),
	`startedAt` timestamp NOT NULL,
	`finishedAt` timestamp,
	`latitude` decimal(10,7),
	`longitude` decimal(10,7),
	`gpsAccuracy` decimal(8,2),
	`language` enum('es','en') NOT NULL DEFAULT 'es',
	`status` enum('completa','incompleta','rechazada','sustitucion') NOT NULL DEFAULT 'completa',
	`earlyExit` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`v01` text,
	`v02` text,
	`v03` text,
	`v04` text,
	`v05` text,
	`v06` text,
	`v07` text,
	`v08` text,
	`v09` text,
	`v10` text,
	`v11` text,
	`v12` text,
	`v13` text,
	`v14` text,
	`v15` text,
	`v16` text,
	`v17` text,
	`v18` text,
	`v19` text,
	`v20` text,
	`v21` text,
	`v22` text,
	`v23` text,
	`v24` text,
	`v25` text,
	`v26` text,
	`r01` text,
	`r02` text,
	`r03` text,
	`r04` text,
	`r05` text,
	`r06` text,
	`r07` text,
	`r08` text,
	`r09` text,
	`r10` text,
	`r11` text,
	`r12` text,
	`r13` text,
	`r14` text,
	`r15` text,
	`r16` text,
	`r17` text,
	`r18` text,
	`r19` text,
	`r20` text,
	`r21` text,
	`r22` text,
	`r23` text,
	`r24` text,
	`r25` text,
	`r26` text,
	`r27` text,
	`r28` text,
	`r29` text,
	`r30` text,
	`r31` text,
	`r32` text,
	`r33` text,
	`r34` text,
	`r35` text,
	`r36` text,
	`r37` text,
	`r38` text,
	CONSTRAINT `survey_responses_flat_id` PRIMARY KEY(`id`)
);
