ALTER TABLE `survey_responses` ADD `windowCode` varchar(16);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `minuteStart` int;--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `minuteEnd` int;--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `earlyExit` boolean DEFAULT false;--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `v_p01` varchar(255);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `v_p02` varchar(255);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `v_p03` varchar(64);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `v_p04` varchar(64);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `v_p05` varchar(64);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `v_p06` varchar(64);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `v_p07` varchar(64);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `v_p08` varchar(255);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `v_p09` varchar(64);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `v_p10` varchar(64);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `v_p11` varchar(64);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `v_p12` varchar(64);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `v_p13` varchar(64);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `v_p14` varchar(8);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `v_p15` varchar(8);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `v_p16` varchar(8);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `v_p17` varchar(64);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `v_p18` varchar(64);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `v_p19` text;--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `v_p20` varchar(255);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p01` varchar(16);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p02` varchar(255);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p03` varchar(64);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p04` varchar(64);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p05` varchar(64);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p06` varchar(64);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p07` varchar(8);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p08` varchar(8);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p09` varchar(8);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p10` varchar(8);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p11` varchar(8);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p12` varchar(8);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p13` varchar(8);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p14` varchar(8);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p15` varchar(8);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p16` varchar(8);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p17` varchar(8);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p18` varchar(8);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p19` varchar(8);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p20` varchar(8);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p21` varchar(8);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p22` varchar(8);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p23` varchar(64);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p24` varchar(64);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p25` varchar(64);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p26` varchar(64);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p27` varchar(64);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p28` varchar(64);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p29` varchar(255);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p30` varchar(8);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p31` varchar(8);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p32` varchar(8);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p33` varchar(8);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p34` varchar(8);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p35a` varchar(64);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p35b` varchar(64);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p35c` varchar(64);--> statement-breakpoint
ALTER TABLE `survey_responses` ADD `r_p36` text;